name: seldonite
channels:
  - conda-forge
dependencies:
  - python=3.7
  - conda-build
  - conda-pack==0.3.1
  - newspaper3k
  - boto3
  - pyspark==3.1.2
  - selenium
  - spacy
  - gensim
  - google-api-python-client
  - pandas==1.0.3
  - numpy==1.21.4
  - six==1.16.0
  - py4j==0.10.9
  - pytest
  - pip
  - pip:
    - -e .
    - warcio
    - ray==1.2.0
    - tensorflow>=2.1.0
    - https://downloads.sourceforge.net/project/analytics-zoo/orca-py-spark3/bigdl_orca_spark3-0.14.0b20211215-py3-none-manylinux1_x86_64.whl
    - https://downloads.sourceforge.net/project/analytics-zoo/dllib-py-spark3/bigdl_dllib_spark3-0.14.0b20211215-py3-none-manylinux1_x86_64.whl
