name: seldonite_spark_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - newspaper3k
  - boto3
  - pyspark
  - selenium
  - spacy
  - gensim
  - google-api-python-client
  - conda-build
  - conda-pack
  - pandas
  - pip
  - pip:
    - ../../.
    - warcio

# tests
  - pytest>=6.2.3
