name: seldonite_spark
channels:
  - conda-forge
dependencies:
  - python=3.7
  - newspaper3k
  - boto3
  - pyspark=3
  - conda-build
  - conda-pack
  - pandas==1.0.3
  - numpy==1.21.4
  - six==1.16.0
  - pip
  - pip:
    - ../../.
    - warcio
    - ray==1.2.0
    - tensorflow>=2.1.0
