name: seldonite_spark
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - conda-build
  - conda-pack==0.3.1
  - newspaper3k
  - boto3
  - pyspark==3.1.2
  - pandas==1.2.5
  - numpy==1.21.4
  - six==1.16.0
  - py4j==0.10.9
  - aioredis<2
  - pip
  - pip:
    - ../../.
    - warcio
    - ray[default]
    - pyzmq
    - tensorflow>=2.1.0
    - bigdl-orca-spark3
    - bigdl-dllib-spark3
    - flashgeotext